### ISSUE TITLE
View path not found

### ISSUE THREAD

**Issue by chinleung** [matthewbdaly/artisan-standalone#1]
When I run execute the command from step 2:

```
vendor/bin/artisan app:name InsertYourProjectNameHere
```

I get the following error:

> In ViewClearCommand.php line 57:
> View path not found.

**Comment by chinleung** [comment]
@matthewbdaly Updated to **artisan-standalone** to **0.0.8** with `composer update` but I'm still receiving the same error.

**Comment by matthewbdaly** [comment]
OK, think I've found the issue.

It looks to be just missing the folder for compiled views, so you should be able to resolve it in an existing repository by running `mkdir -p storage/framework/views`. I'll amend the `composer.json` to create the missing directories.

**Comment by matthewbdaly** [comment]
Fix is in `laravel-package-boilerplate`, so now it should work as expected.

**Comment by chinleung** [comment]
@matthewbdaly It works when I create the views folder manually. However, if I create a new project over with the `laravel-package-boilerplate`, I still get the same error.

**Comment by matthewbdaly** [comment]
OK, I think I found the issue and have deployed a new version to Packagist. I can no longer reproduce the issue. Can you confirm the same?

**Comment by chinleung** [comment]
> OK, I think I found the issue and have deployed a new version to Packagist. I can no longer reproduce the issue. Can you confirm the same?

Yes everything works fine now! 👍
