### ISSUE TITLE
Seems array cache is being ignored?

### ISSUE THREAD

**Issue by roblesterjr04** [matthewbdaly/artisan-standalone#2]
I get this error: `In PackageManifest.php line 168: ... bootstrap/cache directory must be present and writable.`

**Comment by matthewbdaly** [comment]
Yes, the specified directory must exist and be editable.

I normally use this package in conjunction with `matthewbdaly/laravel-package-boilerplate`, which is set up to create that directory on install. It could possibly do with having a more general solution, though.

How are you using it? Have you pulled it in as a dev dependency on a package you're working on?

**Comment by roblesterjr04** [comment]
Well, i realized i wasn't actually using array cache - i have a .env file ignored but present locally in the project that i use for running unit tests (sensitive keys) - It was setting the cache to file. Anyway, i created and ignored the bootstrap/cache directory and the artisan console works, but it won't really work for me because i ultimately was trying to get tinker to work.

**Comment by matthewbdaly** [comment]
Yes, the main intent of this package is to make the generator commands work. It's not really set up to work with a database. Though I could take a look this weekend and see how practical it might be to do that.

**Comment by matthewbdaly** [comment]
Just FYI, I've been able to resolve this issue, at least with `laravel-package-boilerplate`. It now pulls in Tinker by default, and I've added the config files for the database, so it should support working with the database as you'd normally expect.

If you're able to verify that it works for your use case, that would be great.
